### ISSUE TITLE
Switching to Grid view and back loses cursor focus until tab switch

### ISSUE THREAD

**Issue by Treeways** [CCDirectLink/CCModManager#5]
On a controller, clicking Select and toggling Grid view will switch the view, but then makes every mod unselectable until a new tab is opened with `LB`.

Attempting to select a mod with the mouse also does not work after changing views with the controller.

**Comment by Treeways** [comment]
https://github.com/user-attachments/assets/bc041c41-a085-46c5-8523-99f567b1be69

**Comment by Treeways** [comment]
Fixed in 0.9.20 - thanks!

**Comment by krypciak** [comment]
wait what how I did nothing
