### ISSUE TITLE
Double-bound LB/RB controller binds

### ISSUE THREAD

**Issue by Treeways** [CCDirectLink/CCModManager#6]
`LB` is double bound both to tab switching and to switching to a test version in Online mods.

`RB` is double bound to tab switching and opening the Mod Settings for enabled mods.

These options should be rebound to `LT`/`RT`.

**Comment by Treeways** [comment]
https://github.com/user-attachments/assets/fb3a717e-84e7-4262-95be-96f8f48418a6

**Comment by krypciak** [comment]
The `Testing` button IS bound to LT, not LB.
Perhaps you have `CCExtraGamepadOptions`?
It is known to break some things unexpectedly.

**Comment by Treeways** [comment]
Just confirmed that the bug does indeed happen with only CCModManager toggled.

![image](https://github.com/user-attachments/assets/16c5a7c2-71e3-4054-87f3-d3fcd6c7297e)

Note that I'm using an Xbox One S controller on Fedora Linux 40.

**Comment by krypciak** [comment]
Do you open the quick menu with LT (L2) or LB (L1)?

**Comment by Treeways** [comment]
My quick menu opens with LB:
![image](https://github.com/user-attachments/assets/949459bf-3dcd-4592-bb26-25cef76668da)

**Comment by Treeways** [comment]
It seems that changing the gamepad settings here do indeed invert my mod manager menu controls per-button. (For a while, my LB button was a little bit finnicky, hence why I decided to swap it out here.)

**Comment by krypciak** [comment]
Should be fixed in the next update

**Comment by Treeways** [comment]
Yep, LGTM. Thanks!
