### ISSUE TITLE
Error？Could not load plugin of mod 'ccmodmanager'

### ISSUE THREAD

**Issue by Emperors-Children** [CCDirectLink/CCModManager#8]
Could not load plugin of mod 'ccmodmanager':  TypeError: Failed to fetch dynamically imported module: chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/mods/CCModManager-0.9.21/plugin.js
TypeError: Failed to fetch dynamically imported module: chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/mods/CCModManager-0.9.21/plugin.js

Could not load plugin of mod 'nax-ccuilib':  TypeError: Failed to fetch dynamically imported module: chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/mods/nax-ccuilib-1.2.9/nax-ccuilib/plugin.js
TypeError: Failed to fetch dynamically imported module: chrome-extension://lmepkikdgdbfdpjokdmnnanopegnpjda/assets/mods/nax-ccuilib-1.2.9/nax-ccuilib/plugin.js

am I missing something?

**Comment by krypciak** [comment]
Please download mods from their release page if it has one
https://github.com/CCDirectLink/CCModManager/releases/tag/v0.9.21
https://github.com/conorlawton/nax-ccuilib/releases/tag/v1.2.9

**Comment by Emperors-Children** [comment]
both mods are the latest versions, and so is the ccloader, but this issue still occurs

**Comment by krypciak** [comment]
Did you download the `.ccmod` files or the zip? The `.ccmod` files are the correct ones.

**Comment by Emperors-Children** [comment]
oh yes, there's no problem downloading ccmod now. thank you for your answer
